version: '3'

services: 
   blazegraphromedi:
    image: lyrasis/blazegraph:2.1.4
    container_name: blazegraphRomedi
    volumes:
      - ./data:/data
    ports:
     - 127.0.0.1:8889:8080
   
   webserver:
    image: tomcat:8.5
    container_name: tomcatRomedi
    ports: 
     - 8892:8080
    depends_on:
     - blazegraphromedi
